name: mzbsuite
channels:
  - conda-forge
  - nodefaults

dependencies:
  - python=3.10
  - numpy=2.2
  - pandas=2.3
  - pytorch=2.10
  - torchvision=0.25
  # - pytorch-cuda
  - pytorch-lightning=2.6
  - matplotlib=3.10
  - scikit-learn=1.7
  - scikit-image=0.25
  - ipython=8.37
  - ipykernel=7.2
  - scipy=1.15
  - pip=26.0

  - pip:
    - pyyaml>=6.0
    - wandb>=0.25
    - opencv-python>=4.13
    - segmentation_models_pytorch>=0.5
    - tensorboard>=2.20
    - tensorboardX>=2.6
    # - sphinx
    # - sphinx-collections
    # - sphinx-rtd-theme
    # - nbsphinx
    - -e .